[package]
version = "0.1.0"
name = "sp1-pay-program"
edition = "2021"

[dependencies]
alloy-primitives = {workspace = true}
alloy-sol-types = {workspace = true}
sha2 = {workspace = true}
sp1-zkvm = {workspace = true}
oidc-validator = {workspace = true}
common = {workspace = true}